name: deploy-toy-website
concurrency: toy-company

# --> Manual trigger
on: [workflow_dispatch] 
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'deploy/**'

env:
    AZURE_RESOURCEGROUP_NAME: ToyWebsite
    ENVIRONMENT: nonprod

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2
      - name: Run Bicep linter
          run: bicep build deploy/main.bicep

  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Sign in to Azure
        uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run preflight validation
        uses: azure/arm-deploy@v1
          with:
            deploymentName: ${{ github.run_number }}
            resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
            template: ./deploy/main.bicep
            parameters: environmentType=${{ env.ENVIRONMENT }}
            deploymentMode: Validate

  Preview:
    runs-on: ubuntu-latest
    needs: [Lint, Validate]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Sign in to Azure
        uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run what-if
        uses: Azure/cli@v1
          with:
            inlineScript: |
              az deployment group what-if \
                --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
                --template-file deploy/main.bicep \
                --parameters environmentType=${{ env.ENVIRONMENT }}

  Deploy:
    runs-on: ubuntu-latest
    environment: Website
    needs: Preview
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Sign in to Azure
        uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy website
        uses: azure/arm-deploy@v1
          with:
            failOnStdErr: false
            deploymentName: ${{ github.run_number }}
            resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
            template: ./deploy/main.bicep
            parameters: environmentType=${{ env.ENVIRONMENT }}